"use client";
import "./globals.css";
import Header from "@/components/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Provider } from "react-redux";
import store from "@/redux/store/store";
import AuthProvider from "@/components/authProvider/AuthProvider";
import MolaPopup from "@/components/MolaPopup";
import { useSelector } from "react-redux";
import FoodPopup from "@/components/FoodPopup";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function Layout({ children }) {
  const foodPopupState = useSelector(state => state.global.foodPopupState)
  const isMolaPopup = useSelector((state) => state.global.isMolaPopup);
  return (
    <>
      <Header />
      <main className="relative">{children}</main>
      {isMolaPopup && <MolaPopup />}
      {foodPopupState && <FoodPopup/>}
      <ToastContainer />
    </>
  );
}



export default function RootLayout({ children }) {

  return (
    <html lang="tr">
      <body>
        <Provider store={store}>
          <AuthProvider>
          <Layout>{children}</Layout>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
