'use client'
import "./globals.css";
import Header from "@/components/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Provider } from "react-redux";
import store from "@/redux/store/store";
import AuthProvider from "@/components/authProvider/AuthProvider";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>
      <Provider store={store}>
          <AuthProvider>
            <Header />
            <main className="relative">{children}</main>
            <ToastContainer />
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
